import type { Metadata, Viewport } from 'next';
// import { Noto_Sans_KR } from 'next/font/google';
import localFont from 'next/font/local';
import '@/styles/globals.scss';
import '@/styles/thirdparty.scss';
import styles from '@/styles/layout.module.scss';
import Nav from '@/ui/layout/Nav';
import Actions from '@/ui/layout/Actions';
import SessionProvider from '@/ui/auth/AppSessionProvider';
import { AppSessionProvider } from '@/ui/auth/AppSessionContext';
import ReactQueryProviders from '@/services/ReactQueryProviders';

// const notosans = Noto_Sans_KR({
//   subsets: ['latin'],
// });

const pretendard = localFont({
  src: '../styles/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <SessionProvider>
          <AppSessionProvider>
            <div className={styles.contents}>
              <header className={styles.header}>
                <a id="skip-nav" className={styles.skip_nav} href="#content">
                  메뉴 건너뛰기
                </a>
                <div className={styles.header_area}>
                  <div>HOME</div>
                  <Nav />
                  <Actions />
                </div>
              </header>
              <ReactQueryProviders>
                <div id="content">{children}</div>
                {auth}
              </ReactQueryProviders>
            </div>
          </AppSessionProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
